title:
  archive: 时间轴
  category: 分类
  tag: 标签
  schedule: 日程

author: 作者

menu:
  home: 首页
  archives: 时间轴
  categories: 分类
  tags: 标签
  about: 关于
  search: 站内搜索
  schedule: 日程
  sitemap: 站内地图
  commonweal: Commonweal 404

sidebar:
  overview: Overview
  toc: Table of Contents

post:
  created: Post created
  modified: Post modified
  sticky: Sticky
  posted: Posted on
  in: In
  more: 更多
  read_more: 查看更多
  untitled: 未命名
  toc_empty: This post does not have a Table of Contents
  visitors: Visitors
  wordcount: Words count in article
  min2read: Reading time
  totalcount: Site words total count
  copyright:
    author: Post author
    link: Post link
    license_title: Copyright Notice
    license_content: 'All articles in this blog are licensed under
      <a href="%s" rel="external nofollow" target="_blank">%s</a> unless stating additionally.'

page:
  totally: Totally
  tags: tags

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: 暂无标签
    one: 目前共计1个标签
    other: "目前共计%d个标签"

  categories:
    zero: 暂无分类
    one: 目前共计1个分类
    other: "目前共计%d个分类"

  archive_posts:
    zero: 暂无日志.
    one: 目前共计1篇日志.
    other: "目前共计%d篇日志"

state:
  posts: 日志
  pages: pages
  tags: 标签
  categories: 分类

search:
  placeholder: Searching...

cheers:
  um: 嗯..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: 继续加油.

symbol:
  comma: ', '
  period: '. '
  colon: ':'

reward:
  donate: Donate
  wechatpay: 微信支付
  alipay: 支付宝支付
  bitcoin: Bitcoin
